---
coreID: ID1
lead_ru: RU1
version: 2 # RoutingInfo version
sections:
    - id: 10
      version: 2 # RouteSection version
      departure_station: S
      departure_time: '00:20:00'
      arrival_station: H1
      travel_time: &s1-tt '24:20:00'
      calendar:
        begin: '2021-02-01'
        end: '2021-02-04'
      color: green
      succ:
          - 11
    - id: 11
      version: 2
      departure_station: H1
      arrival_station: T
      travel_time: &s2-tt '07:30:00'

    - id: 40
      version: 1
      departure_station: S
      departure_time: '23:30:00'
      arrival_station: H1
      travel_time: '24:20:00'
      color: yellowgreen
      calendar:
        begin: '2021-02-04'
        end: '2021-02-06'
      succ:
          - 41
    - id: 41
      version: 1
      departure_station: H1
      arrival_station: T
      travel_time: '07:30:00'

    # Sec 3-4: Shorten calender
    # Change departure times
    - id: 20
      version: 2
      departure_station: S
      departure_time: '23:55:00'
      arrival_station: H1
      travel_time: *s1-tt
      color: blue
      calendar:
        begin: '2021-02-11'
        end: '2021-02-13'
      succ:
          - 21
    - id: 21
      version: 2
      departure_station: H1
      arrival_station: T
      travel_time: *s2-tt

    # Shorten calender of D-T
    - id: 50
      version: 1
      departure_station: D
      departure_time: '01:45:00'
      arrival_station: H1
      travel_time: '22:30:00'
      color: red
      calendar:
        begin: '2021-02-08'
        end: '2021-02-11'
      succ:
          - 51
    - id: 51
      version: 1
      departure_station: H1
      arrival_station: T
      travel_time: *s2-tt

    - id: 30
      version: 2
      departure_station: D
      departure_time: '01:10:00'
      arrival_station: H1
      travel_time: '22:30:00'
      color: salmon
      calendar:
        begin: '2021-02-15'
        end: '2021-02-20'
      succ:
          - 31
    - id: 31
      version: 2
      departure_station: H1
      arrival_station: T
      travel_time: *s2-tt
