# Config file for automatic testing at travis-ci.org
sudo: false
language: python
python:
  - 3.7
  - 3.6
  - 3.5
  - 3.4
  - 2.7

env:
  global:
  - secure: "<encrypted MYPYPI_USER=username>"
  - secure: "<encrypted MYPYPI_PASS=p@ssword>"

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
- pip install -U poetry
- pip install -U tox-travis 


# Command to run tests, e.g. python setup.py test
script: tox


