@startuml
!include tom-01-overview.puml
@enduml

@startuml
!include tom-02-section.puml
@enduml

@startuml
!include tom-02-calendars.puml
@enduml

@startuml
!include tom-03-section-run.puml
@enduml

' AC-FF
@startuml
!include tom-04-example-ac-ff-infrastructure.puml
@enduml

@startuml
!include tom-04-example-ac-ff.puml
@enduml

' A-F
@startuml
!include tom-05-example-a-f-infrastructure.puml
@enduml

@startuml
!include tom-05-example-a-f.puml
@enduml

' Annex 4
@startuml
!include tom-06-example-annex-4-infrastructure.puml
@enduml

' basis pattern
@startuml
!include rp-05-basic-msg-exchange-pattern.puml
@enduml

' Phase 01 route plan
@startuml
!include rp-10-initial-setup.puml
@enduml

' Phase 02 route update
@startuml
!include rp-20-route-update.puml
@enduml
