title Re-Planning (Lead RU = RU1)
skinparam BoxPadding 25

box "RU1/IM1"
participant RU1 order 10
participant IM1 order 20
end box
box "RU2/IM2"
participant RU2 order 40
participant IM2 order 50
end box

group Harmonisation (Lead RU sends new version (RI-v2) of RoutingInfo to applicant RU2)
    RU1 -> RU2: RIM(RI-v2)
    note left
        Sections updates: {10,20,30}.v2, {11,21,31}.v2
        New       sections: {40,50}.v1, {41,51}.v1
    end note
end
group Inform IM1, IM2 about new RI version
    RU1 -> IM1: RIM(RI-v2)
    RU1 -> IM2: RIM(RI-v2)
end
group "Path Re-Planning RU1/IM1"
    loop "for $i in {10,20,30}"
        RU1 -> IM1: PRM(RI-v2, RS-$i.v2)
    end
    RU1 -> IM1: PRM(RI-v2, RS-11.v1)
    RU1 -> IM1: PRM(RI-v2, RS-31.v1)
    par "for $i in {10,20,30}"
        IM1 -> RU1: PDM(RS-$i.v2)
    end
    IM1 -> RU1: PDM(RS-40.v1)
    IM1 -> RU1: PDM(RS-50.v1)
end
group "Path Re-Planning RU2/IM2"
    loop "for $i in {10,20,30}"
        RU2 -> IM2: PRM(RI-v2, RS-$i.v2)
    end
    RU2 -> IM2: PRM(RI-v2, RS-41.v1)
    RU2 -> IM2: PRM(RI-v2, RS-51.v1)
    par "for $i in {11,21,31}"
        IM2 -> RU2: PDM(RS-$i.v2)
    end
    IM2 -> RU2: PDM(RS-41.v1)
    IM2 -> RU2: PDM(RS-51.v1)
end
