class JourneyLocation <<TOM>> {
    id: LocationIdentifier
}
class Train <<TOM>> {
    lead_ru: CompanyCode
}
class RouteSection {
    planning_im: CompanyCode
    applicant_ ru: CompanyCode
}
Handover --|> JourneyLocation
Origin --|> JourneyLocation
Destination --|> JourneyLocation

RouteSection "*" -> "1" JourneyLocation : origin >
RouteSection "*" -> "1" JourneyLocation : destination >
Train *-- "1..*" RouteSection

class PathRequest <<TOM>> {
    planning_im: CompanyCode
    applicant_ ru: CompanyCode
}
RouteSection o--  "0..*" PathRequest : is derived from <
