left to right direction

class Train {
    core: CoreID
    lead_ru: CompanyCode
    version: int

    +TrainID train_id()
}

class RouteSection {
    departure_station: JourneyLocation
    departure_time: TimeOfDay
    departure_stop_time: timedelta
    ---
    arrival_station: JourneyLocation
    travel_time: timedelta
    calendar: Set<Date>
    ---
    applicant_ru: CompanyCode
    planning_im: CompanyCode
    ---
    section_id: int
    version: int = 1
    ---
    + str section_key()
}

Train *-- "1..*" RouteSection
