left to right direction

class Train <<TOM>> {
    lead_ru: CompanyCode
    +TrainID train_id()
}

class RouteSection {
    applicant_ru: CompanyCode
    planning_im: CompanyCode

    origin_departure_time: TimeOfDay
    calendar: Set<Date>
}
Train *-- "1..*" RouteSection

class SectionRun {

    departure_at_origin: Timestamp
    + str section_id()
    + Timestamp arrival_at_destination()
    + Timestamp arrival_at_origin()
    + JourneyLocation origin()
    + JourneyLocation destination()
    + Boolean connects_to(other: SectionRun)
}
RouteSection *- "1..*" SectionRun
note bottom of SectionRun
    A section run happens on the calendar day
    of its departure_at_origin timestamp.
end note

class TrainRun {
    + TrainID train_run_id()
    + Date start_date()
}
note bottom of TrainRun
    The start_date of a train run is the calendar day
    of the departure_at_origin timestamp of
    its first section run.
end note

TrainRun o--> "1..* {ordered}" SectionRun
Train o- "1..365" TrainRun
