package Prorail <<Rectangle>> {
    object "Amsterdam Central" as ac
    ac : AC
}
package "DB Netz" <<Rectangle>> {
    object "Frankfurt" as ff
    ff : FF
}
package "Handovers" <<Rectangle>> {
    object Venlo
    object "Emmerich" as emm
    emm : EMM
}

ac - emm
ac - Venlo
Venlo - ff
emm - ff
Venlo --[hidden] emm
