left to right direction

class Train {
    core: CoreID
    lead_ru: CompanyCode
    version: int

    +TrainID train_id()
}

class RouteSection {
    origin: JourneyLocation
    origin_departure_time: TimeOfDay
    origin_stop_time: timedelta
    ---
    destination: JourneyLocation
    travel_time_to_destination: timedelta
    calendar: Set<Date>
    ---
    applicant_ru: CompanyCode
    planning_im: CompanyCode
    ---
    section_id: int
    version: int = 1
    ---
    + str section_key()
}

Train *-- "1..*" RouteSection
