left to right direction

class Train <<TOM>> {
    lead_ru: CompanyCode
    +TrainID train_id()
}

class RouteSection {
    applicant_ru: CompanyCode
    planning_im: CompanyCode

    departure_time: TimeOfDay
    calendar: Set<Date>
}
Train *-- "1..*" RouteSection

class SectionRun {

    departure_time: Timestamp
    + str section_id()
    + Timestamp arrival_time()
    + Timestamp arrival_at_departure_station()
    + JourneyLocation departure_station()
    + JourneyLocation arrival_station()
    + Boolean connects_to(other: SectionRun)
}
RouteSection *- "1..*" SectionRun
note bottom of SectionRun
    A section run happens on the calendar day
    of its departure_time timestamp.
end note

class TrainRun {
    + TrainID train_run_id()
    + Date start_date()
}
note bottom of TrainRun
    The start_date of a train run is the calendar day
    of the departure_time timestamp of
    its first section run.
end note

TrainRun o--> "1..* {ordered}" SectionRun
Train o- "1..365" TrainRun
