package IMa <<Rectangle>> {
    object A
    object B
}
object C
C : Handover

package IMb <<Rectangle>> {
    object D
}

object E
E : Handover

package IMc <<Rectangle>> {
    object F
    object G
}

A - B
B - C
C - D
D - E
E - F
F - G
